name: tobias workflow

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  GITHUB_REPOSITORY: ${{ github.repository_owner }}/${{github.repository}}
  WORKFLOW_FILE_NAME: main.yml
  IMAGE: ${{github.repository}}
  VERSION: latest

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.2.2']
    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: 
            pkgdown
            devtools
            roxygen2
            lintr
            formatR
            attachment
            typed
            testthat
      - name: Install
        run:  make install
      - name: Check
        run:  make check ERROR_ON="error"
      - uses: peter-evans/create-pull-request@v4
        with:
          name: Send pull request
          commit_message: Packakge in dev branch passed all the tests
      - name: Deploy 
        run: |
          curl -X POST \
          https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/actions/workflows/${{ env.WORKFLOW_FILE_NAME }}/dispatches \
          -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Accept: application/vnd.github+json" \
          -d '{"ref": "dev", "inputs": { "owner":"${{ github.repository_owner }}", \
          "image":"${{ env.IMAGE }}", "version":"${{ env.VERSION }}" }}'
      

