name: R


on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.2.2']

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run:  |
          sudo apt-get update && \
            sudo apt-get install -y --no-install-recommends \
            build-essential curl libbz2-dev liblzma-dev libcurl4-openssl-dev \
            libxml2-dev libssl-dev libcurl4-openssl-dev
          make init
      - name: Install
        run:  make install
      - name: Check
        run:  make check
      - name: Deploy 
        run: |
          curl -X POST https://api.github.com/repos/the-tobias-project/tobias-R-infra/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - uses: actions/checkout@v3

    