name: R


on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  OWNER: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.2.2']
    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: 
            pkgdown
            devtools
            roxygen2
            lintr
            formatR
            attachment
            typed
            testthat
      - name: Install
        run:  make install
      - name: Check
        run:  make check
      #- name: Test
      #  run:  make test
      - name: Deploy 
        run: |
          curl -X POST https://api.github.com/repos/the-tobias-project/tobias-R-infra/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "name":"tobias", "owner": "'"$OWNER"'" }}'
      - uses: actions/checkout@v3

    