name: tobias workflow


on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      message:
        description: 'Tobias CD'


env:
  GITHUB_REPOSITORY: the-tobias-project/tobias-R-infra
  WORKFLOW_FILE_NAME: main.yml
  IMAGE: tobias
  VERSION: latest

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.2.2']
    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: 
            pkgdown
            devtools
            roxygen2
            lintr
            formatR
            attachment
            typed
            testthat
      - name: Install
        run:  make install
      - name: Check
        run:  make check ERROR_ON="error"
      - name: Deploy 
        run: |
          curl -X POST \
          https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/actions/workflows/${{ env.WORKFLOW_FILE_NAME }}/dispatches \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Accept: application/vnd.github+json" \
          -d '{"event_type": "dev", "client_payload": { "owner":"${{ github.repository_owner }}", "image":"${{ env.IMAGE }}", "version":"${{ env.VERSION }}"}}'

