name: R


on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.1.1', '4.2.2']

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run:  make init
      - name: Install dependencies
        run:  make init REPO=tobias
      - name: Install
        run:  make install REPO=tobias
      - name: Check
        run:  make check REPO=tobias
      - name: Deploy 
        run: |
          curl -X POST https://api.github.com/repos/the-tobias-project/tobias-R-infra/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - uses: actions/checkout@v3

    