name: sec10k

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: tobias
  VERSION: latest

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare the environment
        run: make pre_CI
      - name: Build the Docker image
        run: make build
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$VERSION
          docker tag $IMAGE_NAME:$VERSION $IMAGE_ID
          docker push $IMAGE_ID
      - name: Run the Docker image
        run: make install && sleep 180 && make wait
      - name: Test the Docker image
        run: make test
      #- uses: stefanzweifel/git-auto-commit-action@v4
      #  with:
      #    commit_message: Apply CI changes
      #    branch: dev
  
  cleanup:
    name: cleanup
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: docker pull ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$VERSION
      - name: Run container
        run: make install
      - name: Wait
        run: sleep 120 && make wait
      - name: Prepare the environment
        run: make pre_CI
      - name: Check linter
        if: always()
        run: make linter; exit 0
      - name: Check static
        if: always()
        run: make static; exit 0
      - uses: peter-evans/create-pull-request@v4
        with:
          name: Send pull request
          commit_message: Packakge in dev branch passed all the tests
